name: Merging of Feature Branch into Develop Branch
on:
  push:
    branches:
      - 'feature**'

permissions:
  contents: write
  pull-requests: write

jobs:
  android-tests:
    name: Android Tests
    if: ${{ contains(github.event.head_commit.message, 'DEPLOY') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to feature branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Merge Develop into feature branch
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: develop
          target-branch: ${{ github.ref }}

      - name: Set up JDK for Android
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          target: 'android-33'
          build-tools: '33.0.2'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run Android unit tests
        id: run-tests
        run: |
          ./gradlew testDebugUnitTest || echo "NO-SOURCE" > result.txt

      - name: Fail job if no tests were found
        if: success() && steps.run-tests.outputs.outcome == 'NO-SOURCE'
        run: |
          echo "No unit tests found! Failing the job."
          exit 1

      - name: Merge feature branch into Develop
        if: success()
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: ${{ github.ref }}
          target-branch: develop
